### ISSUE TITLE
Crashing/hanging issue

### ISSUE THREAD

**Issue by E85Addict** [D3SOX/vc-betterActivities#5]
I believe due to the commit [a4a0043](https://github.com/D3SOX/vc-betterActivities/commit/a4a0043e7ce592d8a11a1a54fd049f1b2abb80b0) its causes hanging and crashes. I can reproduce this by simply having my own profile open while an activity is open and changing it or starting or ending the activity even spotify starting and ending causes it to crash. When I turn off this plugin, the crashes stop. It seems to simply be tied to ones own profile, everyone elses profile is fine, it's whenever I view my own profile.

**Comment by D3SOX** [comment]
I've tried to open the popout for my profile and starting/stopping Spotify but I can't notice any lags or crashes.
Is there anything meaningful logged to the console when this happens?
Did you try to revert that commit and see if it works for you again?

**Comment by E85Addict** [comment]
`web.02eb93813621b8fa0106.js:12 Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at aO (web.02eb93813621b8fa0106.js:12:990683)
    at Object.aq [as useMemo] (web.02eb93813621b8fa0106.js:12:994368)
    at t.useMemo (web.02eb93813621b8fa0106.js:12:1108287)
    at showAllActivitiesComponent (index.tsx:338:30)
    at aA (web.02eb93813621b8fa0106.js:12:990088)
    at sh (web.02eb93813621b8fa0106.js:12:1001987)
    at l (web.02eb93813621b8fa0106.js:12:1046221)
    at ok (web.02eb93813621b8fa0106.js:12:1028319)
    at web.02eb93813621b8fa0106.js:12:1028185
    at oG (web.02eb93813621b8fa0106.js:12:1028193)
se @ web.02eb93813621b8fa0106.js:12
a.componentDidCatch.n.callback @ web.02eb93813621b8fa0106.js:12
iK @ web.02eb93813621b8fa0106.js:12
s$ @ web.02eb93813621b8fa0106.js:12
e @ web.02eb93813621b8fa0106.js:12
(anonymous) @ web.02eb93813621b8fa0106.js:12
oF @ web.02eb93813621b8fa0106.js:12
oO @ web.02eb93813621b8fa0106.js:12
N @ web.02eb93813621b8fa0106.js:12
L @ web.02eb93813621b8fa0106.js:12
T.C.<computed> @ web.02eb93813621b8fa0106.js:1
D @ web.02eb93813621b8fa0106.js:1
b @ web.02eb93813621b8fa0106.js:1
web.02eb93813621b8fa0106.js:12 `
    
`GET https://discord.com/api/v9/users/@me/affinities/v2/users 404 (Not Found)
A._end @ web.02eb93813621b8fa0106.js:12
A.end @ web.02eb93813621b8fa0106.js:12
(anonymous) @ web.02eb93813621b8fa0106.js:12
l.then @ web.02eb93813621b8fa0106.js:12
E @ web.02eb93813621b8fa0106.js:12
(anonymous) @ web.02eb93813621b8fa0106.js:12
I @ web.02eb93813621b8fa0106.js:12
s @ f02744aebc880110be69.js:1
(anonymous) @ e16ee489b3d4e16eb209.js:1
sF @ web.02eb93813621b8fa0106.js:12
oV @ web.02eb93813621b8fa0106.js:12
oD @ web.02eb93813621b8fa0106.js:12
r5 @ web.02eb93813621b8fa0106.js:12
(anonymous) @ web.02eb93813621b8fa0106.js:12
oF @ web.02eb93813621b8fa0106.js:12
oO @ web.02eb93813621b8fa0106.js:12
N @ web.02eb93813621b8fa0106.js:12
L @ web.02eb93813621b8fa0106.js:12
T.C.<computed> @ web.02eb93813621b8fa0106.js:1
D @ web.02eb93813621b8fa0106.js:1
b @ web.02eb93813621b8fa0106.js:1
`

**Comment by E85Addict** [comment]
[discord.com-1722413313329.log](https://github.com/user-attachments/files/16438304/discord.com-1722413313329.log)

**Comment by E85Addict** [comment]
I can confirm reverting the commit stops the crash.

**Comment by D3SOX** [comment]
Can you enable ReactErrorDecoder and post the log again

**Comment by E85Addict** [comment]
> Can you enable ReactErrorDecoder and post the log again

Gotcha here it is with the ReactErrorDecoder enabled. 
[discord.com-1722465162914.log](https://github.com/user-attachments/files/16447763/discord.com-1722465162914.log)

**Comment by D3SOX** [comment]
Thanks, will look into this soon

**Comment by D3SOX** [comment]
I was able to reproduce and fix it now

**Comment by 49ylp** [comment]
it came back again

**Comment by D3SOX** [comment]
@49ylp What do you mean? The same error? Please open a new issue with a more detailed description of your profile.
